// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgiWQEZE5Z2zfZ6MeY5lSfSyRKRsodMLY',
    appId: '1:844984387565:web:c53895155ca3627bd349e4',
    messagingSenderId: '844984387565',
    projectId: 'breast-cancer-prediction-42ecb',
    authDomain: 'breast-cancer-prediction-42ecb.firebaseapp.com',
    storageBucket: 'breast-cancer-prediction-42ecb.appspot.com',
    measurementId: 'G-9S9FEKR6E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy38JWpi7vN61mmf5m-5H9N499pH4rnDw',
    appId: '1:844984387565:android:5394dcc38c655e4ad349e4',
    messagingSenderId: '844984387565',
    projectId: 'breast-cancer-prediction-42ecb',
    storageBucket: 'breast-cancer-prediction-42ecb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1TxjU4jXjUMPPptQfxMJUdIJFDWUoobk',
    appId: '1:844984387565:ios:6c65ef0c79b7a9d9d349e4',
    messagingSenderId: '844984387565',
    projectId: 'breast-cancer-prediction-42ecb',
    storageBucket: 'breast-cancer-prediction-42ecb.appspot.com',
    iosClientId: '844984387565-l302e8kqdo525ro3s47u49f3r82phu3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.breastCancerPrediction',
  );
}
